### PR TITLE
simplify website, remove guides etc

### PR DESCRIPTION
**Pull request by joehand**
Removes most of the old content.

@pfrazee want to add the autogen part here? We can either have an index on homepage or link to another index page - either is fine with me.

We may want to wait until there is a DEP to show =).

### CODE REVIEW

**Comment by pfrazee** [comment]
Yeah I'll wait for our first DEP to land

**Comment by joehand** [comment]
Okay, added the autogeneration! Pretty simple for now: [view site](https://5a7f2cf5fd0efa67466312cd--datprotocol.netlify.com/)

**Comment by pfrazee** [comment]
Nice!

**Comment by joehand** [comment]
Do we only want to display **accepted** DEPs, not draft? Or some way to distinguish draft vs active on the index page?

Edit: Oh accepted isn't a term we defined. Its draft and active....

**Comment by pfrazee** [comment]
I suggest we display drafts and indicate status

**Comment by joehand** [comment]
Added status to index:

screen shot 2018-02-12 at 12 45 11 pm

**Comment by pfrazee** [comment]
Solid

**Pull request merged**
